version: '3'
services:
  datajoint_test:
    build: .
    container_name: ibl_datajoint_test
    env_file: .env_test
    volumes:
      - ./notebooks:/home/dja
      - ./images:/images
      - .:/src/IBL-pipeline
      - ./data:/data
      - ./root/.one_params:/root/.one_params
    user: 1000:anaconda
    ports:
      - "9999:8888"
    networks:
      - ibl_test
networks:
  ibl_test:
