version: '3'
services:
  datajoint_updates:
    build: .
    container_name: ibl_datajoint
    env_file: .env_update
    volumes:
      - ./notebooks:/home/dja
      - ./images:/images
      - .:/src/IBL-pipeline
      - ./data:/data
      - ./root/.one_params:/root/.one_params
    user: 1000:anaconda
    ports:
      - "8902:8888"
    networks:
      - ibl_update

networks:
  ibl_update:
