version: '3'
services:
  datajoint_dbtest:
    build: .
    container_name: ibl_datajoint_dbtest
    env_file: .env_dbtest
    volumes:
      - ./notebooks:/home/dja
      - ./images:/images
      - .:/src/IBL-pipeline
      - ./data:/data
      - ./root/.one_params:/root/.one_params
    user: 1000:anaconda
    ports:
      - "8920:8888"
    networks:
      - ibl_dbtest
networks:
  ibl_dbtest:
