version: '3'
services:
  datajoint:
    build: .
    environment:
      - DJ_HOST=db
      - DJ_USER=root
      - DJ_PASS=simple
    volumes:
      - ./notebooks:/home/dja
      - ./images:/images
      - .:/src/IBL-pipeline
      - ./data:/data
      - ./root/.one_params:/root/.one_params
    links:
      - db
    user: 1000:anaconda
    ports:
      - "8888:8888"
    networks:
      - ibl_local

  db:
    image: datajoint/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=simple
    ports:
      - "4306:3306"
networks:
  ibl_local
