version: '3'
services:
  datajoint:
    build: .
    env_file: .env
    volumes:
      - ./notebooks:/home/dja
      - ./images:/images
      - .:/src/IBL-pipeline
      - ./data:/data
      - ./root/.one_params:/home/dja/.one_params
    user: 1000:anaconda
    ports:
      - "8888:8888"
    networks:
      - ibl
networks:
  ibl:
